### ISSUE TITLE
Sticky does not open anymore

### ISSUE THREAD

**Issue by floxo115** [linuxmint/sticky#114]
Original exception was:
Traceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 678, in do_activate
    self.file_handler = FileHandler(self.settings, self.dummy_window)
  File "/usr/lib/sticky/common.py", line 44, in __init__
    self.load_notes()
  File "/usr/lib/sticky/common.py", line 52, in load_notes
    info = json.loads(file.read())
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 1: invalid continuation byte

**Comment by tpmccrary** [comment]
I am having the exact same issue. I have tried un-installing and re-installing to no avail. 

It Only opens when I run `sudo sticky`...

**Comment by Brianw6621** [comment]
Ok, so nearly a year after the last comment, I too had this problem of Sticky not running/opening. 

After quite a bit of uninstall/install/deleting as per comments above, I stumbled on a solution that worked for me and hopefully will work for others too.

In the .config file of Sticky there's a default file called notes (This location also contains any automatic backups that have been made). I made a copy of this file (just in case), then deleted the original. Re-ran the program and it ran as expected, creating a new default notes file in the process. Using the Import command I imported the latest auto-backup file and I now have Sticky up and running, with all notes present.

**Comment by jdalbey** [comment]
I also get the error reported here if I manually corrupt the notes.json file.  It seems that sticky doesn't have a graceful way of responding to a corrupt notes file. I agree it would be nice if this edge case were dealt with more intelligently.  
Perhaps retitle this issue?  Something like "Sticky crashes on corrupt notes file".
