### ISSUE TITLE
Interacting with tray menu often crash with segmentation fault

### ISSUE THREAD

**Issue by fruxo** [linuxmint/sticky#123]
On my new computer, sticky is very instable and crash very often. No python stack. It's something with gtk.
First I thought it was when switching group from the tray menu, but it turns out the bug has something to do with the tray menu itself.
I can reproduce just by clicking the right mouse button on the menu a few times, and the crash happens!

**System info:**
```
Manjaro Linux
Cinnamon 6.0.4
Kernel 6.6.10-1-MANJARO
AMD Ryzen 9 7950X 16-Core Processor × 16
X11

```

**Stack:**

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff6b68ea8 in g_type_check_instance_is_a () from /usr/lib/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff6b68ea8 in g_type_check_instance_is_a () at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff5a280e7 in  () at /usr/lib/libgdk-3.so.0
#2  0x00007ffff59ccfa9 in gdk_display_get_event () at /usr/lib/libgdk-3.so.0
#3  0x00007ffff5a283d8 in  () at /usr/lib/libgdk-3.so.0
#4  0x00007ffff6c0df69 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff6c6c367 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff6c0c162 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff6999b66 in g_application_run () at /usr/lib/libgio-2.0.so.0
#8  0x00007ffff7e204f6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#9  0x00007ffff7e1cf5e in ffi_call_int (cif=cif@entry=0x55555668a6f8, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0)
    at ../src/x86/ffi64.c:673
#10 0x00007ffff7e1fb73 in ffi_call (cif=cif@entry=0x55555668a6f8, fn=<optimized out>, rvalue=rvalue@entry=0x7fffffffd6f8, avalue=<optimized out>)
    at ../src/x86/ffi64.c:710
#11 0x00007ffff75f56d1 in pygi_invoke_c_callable (function_cache=0x55555668a650, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>)
    at ../pygobject/gi/pygi-invoke.c:684
#12 0x00007ffff75f4090 in pygi_function_cache_invoke (py_kwargs=0x7ffff4466bc0, py_args=0x7ffff445d630, function_cache=<optimized out>)
    at ../pygobject/gi/pygi-cache.c:862
#13 pygi_callable_info_invoke (user_data=0x0, cache=<optimized out>, kwargs=0x7ffff4466bc0, py_args=0x7ffff445d630, info=<optimized out>)
    at ../pygobject/gi/pygi-invoke.c:727
#14 _wrap_g_callable_info_invoke (self=<optimized out>, py_args=0x7ffff445d630, kwargs=0x7ffff4466bc0) at ../pygobject/gi/pygi-invoke.c:764
#15 0x00007ffff7a16846 in _PyObject_Call (kwargs=<optimized out>, args=0x7ffff445d630, callable=0x7ffff5e25830, tstate=0x7ffff7d89378 <_PyRuntime+166328>)
    at Objects/call.c:343
#16 PyObject_Call (callable=0x7ffff5e25830, args=0x7ffff445d630, kwargs=<optimized out>) at Objects/call.c:355
#17 0x00007ffff79e8f3d in do_call_core (use_tracing=<optimized out>, kwdict=0x7ffff4466bc0, callargs=0x7ffff445d630, func=0x7ffff5e25830, tstate=<optimized out>)
    at Python/ceval.c:7343
#18 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:5367
#19 0x00007ffff7a9c484 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff7f9f020, tstate=0x7ffff7d89378 <_PyRuntime+166328>) at ./Include/internal/pycore_ceval.h:73
#20 _PyEval_Vector
    (tstate=tstate@entry=0x7ffff7d89378 <_PyRuntime+166328>, func=func@entry=0x7ffff6e11bc0, locals=locals@entry=0x7ffff6ff2d80, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:6425
#21 0x00007ffff7a9be6c in PyEval_EvalCode (co=0x55555583a6f0, globals=<optimized out>, locals=0x7ffff6ff2d80) at Python/ceval.c:1140
#22 0x00007ffff7ab9fc3 in run_eval_code_obj
    (tstate=tstate@entry=0x7ffff7d89378 <_PyRuntime+166328>, co=co@entry=0x55555583a6f0, globals=globals@entry=0x7ffff6ff2d80, locals=locals@entry=0x7ffff6ff2d80)
    at Python/pythonrun.c:1710
#23 0x00007ffff7ab63ea in run_mod
    (mod=mod@entry=0x55555582df20, filename=filename@entry=0x7ffff6f2d0d0, globals=globals@entry=0x7ffff6ff2d80, locals=locals@entry=0x7ffff6ff2d80, flags=flags@entry=0x7fffffffdc48, arena=arena@entry=0x7ffff6f1b7b0) at Python/pythonrun.c:1731
#24 0x00007ffff7acc723 in pyrun_file
    (fp=fp@entry=0x55555555a470, filename=filename@entry=0x7ffff6f2d0d0, start=start@entry=257, globals=globals@entry=0x7ffff6ff2d80, locals=locals@entry=0x7ffff6ff2d80, closeit=closeit@entry=1, flags=0x7fffffffdc48) at Python/pythonrun.c:1626
#25 0x00007ffff7acc095 in _PyRun_SimpleFileObject (fp=0x55555555a470, filename=0x7ffff6f2d0d0, closeit=1, flags=0x7fffffffdc48) at Python/pythonrun.c:440
#26 0x00007ffff7aca958 in _PyRun_AnyFileObject (fp=0x55555555a470, filename=0x7ffff6f2d0d0, closeit=1, flags=0x7fffffffdc48) at Python/pythonrun.c:79
#27 0x00007ffff7ac51f8 in pymain_run_file_obj (skip_source_first_line=0, filename=0x7ffff6f2d0d0, program_name=0x7ffff6ff2f70) at Modules/main.c:360
#28 pymain_run_file (config=0x7ffff7d6f3c0 <_PyRuntime+59904>) at Modules/main.c:379
#29 pymain_run_python (exitcode=0x7fffffffdc40) at Modules/main.c:601
#30 Py_RunMain () at Modules/main.c:680
#31 0x00007ffff7a8e79b in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:734
#32 0x00007ffff7645cd0 in  () at /usr/lib/libc.so.6
#33 0x00007ffff7645d8a in __libc_start_main () at /usr/lib/libc.so.6
#34 0x0000555555555045 in _start ()
(gdb) 

```

**Comment by collinss** [comment]
Fixed in 8013f4c9651b222128c1b3a7311769d4db9dc6a0
