### ISSUE TITLE
unable to create new note

### ISSUE THREAD

**Issue by Iss-in** [linuxmint/sticky#132]
when i click on a new note , getting error

`
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 1001, in new_note
    workarea_rect = Gdk.Monitor.get_workarea(
`

sticky 1.22-1
arch linux 
sway

**Comment by arn9000** [comment]
Same problem 

```
(sticky.py:15131): Gtk-CRITICAL **: 22:28:52.819: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/sticky/sticky.py", line 1001, in new_note
    workarea_rect = Gdk.Monitor.get_workarea(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 0 does not allow None as a value
```

When stucky starts as root. The add note button works well

stucky 1.24
ubuntu 22.10

**Comment by lever1209** [comment]
This issue persists on archlinux under kde wayland, fully up to date as of this post
